NewEmergmed/NewEmergmed/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    re_path(r'^sackett/', include('sackett.urls')),
)

NewEmergmed/sackett/urls.py
from django.urls import re_path
from . import views

app_name = 'sackett'

urlpatterns = [
    re_path(r'debug/import_datatables$', views.debug_import_tables, name='debug_import_tables'),
    re_path(r'debug/import_diagnoses$', views.debug_import_diagnoses, name='debug_import_diagnoses'),
    re_path(r'admin/area/add$', views.add_zone, name='add_zone'),
    re_path(r'admin/area/zoneimg/(?P<image_path>.+\.(jpe?g|gif|png))$', views.zone_image, name='zone_image'),
    re_path(r'arrivals/expected$', views.expected_arrival, name='expected_arrival'),
    re_path(r'arrivals/triage$', views.triage_arrival, name='triage_arrival'),
    # re_path(r'config/language$', views.config_choose_language, name='config_choose_language'),
    re_path(r'episode/(?P<episode_id>[0-9]+)$', views.episode, name='episode'),
    re_path(r'episode/(?P<episode_id>[0-9]+)/patient$', views.patient_details, name='patient_details'),
    re_path(r'episode/(?P<episode_id>[0-9]+)/update$', views.episode_update, name='episode_update'),
    re_path(r'episode/breach/(?P<episode_id>[0-9]+)$', views.episode_breach, name='submit_breach'),
    re_path(r'lock/acquire$', views.lock_acquire, name='lock_acquire'),
    re_path(r'lock/refresh$', views.lock_refresh, name='lock_refresh'),
    re_path(r'lock/release$', views.lock_release, name='lock_release'),
    re_path(r'registration$', views.patient_details_overview, name='patient_details_overview'),
    re_path(r'search/diagnosis/(?P<search>.*)$', views.diagnosis_search, name='diagnosis_search'),
    re_path(r'search/gp/(?P<search>.*)$', views.gp_search, name='gp_search'),
    re_path(r'search/school/(?P<search>.*)$', views.school_search, name='school_search'),
    re_path(r'search/hcfacility/(?P<search>.*)$', views.healthcare_facility_search, name='healthcare_facility_search'),
    re_path(r'user/add/(?P<is_doctor>[0-1])$', views.user_management_add, name='user_management_add'),
    re_path(r'user/delete/(?P<user_id>[0-9]+)$', views.user_management_delete_doctor, name='user_management_delete_doctor'),
    re_path(r'user/disable/(?P<user_id>[0-9]+)$', views.user_management_disable_doctor,
        name='user_management_disable_doctor'),
    re_path(r'user/edit/(?P<user_id>[0-9]+)$', views.user_management_edit_user, name='user_management_edit'),
    re_path(r'user/enable/(?P<user_id>[0-9]+)$', views.user_management_enable_doctor, name='user_management_enable_doctor'),
    re_path(r'user/login$', views.user_management_login, name='login'),
    re_path(r'user/logout$', views.user_management_logout, name='logout'),
    re_path(r'user/manage(/?P<show_inactive>[0-1])?$', views.user_management_all, name='user_management_all'),
    re_path(r'user/profile$', views.user_management_personal, name='user_management_personal'),
    re_path(r'area$', views.zone_summary, name='zone_summary'),
    re_path(r'area/content$', views.zone_summary_content_only, name='zone_summary_content_only'),
    re_path(r'area/(?P<zone_id>[0-9]+)$', views.zone_overview, name='zone_overview'),
    re_path(r'area/(?P<zone_id>[0-9]+)/content$', views.zone_overview_content_only, name='zone_overview_content_only'),
    re_path(r'$', views.zone_summary, name='default'),
    re_path(r'index\.html$', views.zone_summary, name='default_index'),

# still TODO
    re_path(r'admin/discharged$', views.zone_summary, name='view_discharged'),
    re_path(r'admin/export$', views.zone_summary, name='export_data'),
    re_path(r'admin/quality$', views.zone_summary, name='review_breaches'),
    re_path(r'admin/dashboard$', views.zone_summary, name='dashboard'),
    re_path(r'admin/settings$', views.zone_summary, name='modify_org'),
]

NewEmergmed/sackett/models.py
from django.conf import settings
from .fields import *


# TODO magic numbers
def em_care_discharge_information_given_from_db(x):
    return True if x == '787281000000102' else False


def em_care_discharge_information_given_to_db(x):
    return '787281000000102' if x in ('t', 'True', '1', True, 1) else ''


def person_interpreter_rqd_from_db(x):
    return True if x == '315594003' else False


def person_interpreter_rqd_to_db(x):
    return '315594003' if x in ('t', 'True', '1', True, 1) else '315595002'


# TODO add user id once logins are implemented - remember to make this optional though in the case that authentication
# is switched off
class RecordLock(models.Model):
    type = models.IntegerField(null=False)

    record_id = models.IntegerField(null=False)

    state = models.IntegerField(null=False)

    uuid = models.CharField(max_length=36, null=False)

    acquired_date_time = models.DateTimeField(null=False)

    last_refresh_date_time = models.DateTimeField(null=False)


# TODO review all blank=True fields across all models
class UniqueIdentifier(models.Model):
    series = models.CharField(max_length=16, null=False)

    identifier = models.IntegerField(null=False)


class PickListData(models.Model):
    # TableNumber, Code, Description, Group, Sort1, Sort2, Char1, Char2, Bool1
    table_number = models.IntegerField(null=False, db_index=True)

    code = models.CharField(max_length=64, null=False)

    description = models.CharField(max_length=256, null=False)

    group = models.CharField(max_length=64, null=True)

    sort1 = models.IntegerField(null=True)

    sort2 = models.IntegerField(null=True)

    # char1 = models.CharField(max_length=256, null=True)

    # char2 = models.CharField(max_length=256, null=True)

    bool1 = models.BooleanField(null = True)

    bool2 = models.BooleanField(null = True)

    bool3 = models.BooleanField(null = True)

    language_code = models.CharField(max_length=6, null=False)

    class Meta:
        index_together = [
            ["table_number", "code"],
            ["table_number", "description"],
        ]


class DiagnosisDataSearchTerm(models.Model):
    term = models.CharField(max_length=64, null=False)


class DiagnosisData(models.Model):
    group1 = models.CharField(max_length=96, null=False)

    group2 = models.CharField(max_length=96, null=False)

    group3 = models.CharField(max_length=96, null=False)

    sort1 = models.IntegerField(null=False)

    sort2 = models.IntegerField(null=False)

    sort3 = models.IntegerField(null=False)

    description = models.CharField(max_length=128, null=False)

    code = models.CharField(max_length=64, null=False)

    search_terms = models.ManyToManyField(DiagnosisDataSearchTerm)

    injury = models.BooleanField()

    aec = models.BooleanField()

    notifiable_disease = models.BooleanField()

    # TODO special case for 51178009 (SIDS) which forces value in EmCare_Discharge_Status; maybe others in future
    post_macro = models.CharField(max_length=128, null=True)

    language_code = models.CharField(max_length=6, null=False)


class Zone(models.Model):
    # `ZoneId` INT NOT NULL AUTO_INCREMENT, - implied

    # `Label` NVARCHAR(128) NOT NULL,
    label = models.CharField(max_length=128, null=False)

    # `Template` VARCHAR(1024) NOT NULL,
    template = models.CharField(max_length=1024, null=False)

    # 'SummaryTemplate' VARCHAR(1024) NOT NULL,
    summary_template = models.CharField(max_length=1024, null=False)

    # `Deleted` TINYINT(1) NOT NULL,
    deleted = models.BooleanField()

    # Many-many between Zone and User
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.label


class Bed(models.Model):
    # `BedId` INT NOT NULL AUTO_INCREMENT, - implied

    # `ZoneId` INT NOT NULL,
    zone = models.ForeignKey(Zone, on_delete=models.CASCADE, null=False)

    # `TemplateIndex` INT NOT NULL,
    template_index = models.IntegerField(null=False)

    # `BedName` nchar(64) NOT NULL,
    name = models.CharField(max_length=64, null=False)

    # `BedLabel` nchar(128) NOT NULL,
    label = models.CharField(max_length=128, null=False)

    def __str__(self):
        return str(self.zone_id) + " (" + str(self.template_index) + ")"


class Episode(models.Model):
    # `EpisodeId` - implied

    # `PersonGivenName` NVARCHAR(35) NULL,
    person_given_name = models.CharField(db_column='PersonGivenName', max_length=35, null=True, blank=True)

    # `PersonFamilyName` NVARCHAR(35) NULL,
    person_family_name = models.CharField(db_column='PersonFamilyName', max_length=35, null=True, blank=True)

    # `PersonStatedGender` CHAR(1) NULL,
    person_stated_gender = models.CharField(db_column='PersonStatedGender', max_length=18, null=True, blank=True)

    # `PersonBirthDate` INT NULL,
    person_birth_date = models.DateField(db_column='PersonBirthDate', null=True, blank=True)

    # `PersonAgeAtAttendance` DECIMAL(9,2) NULL,
    person_age_at_attendance = models.DecimalField(db_column='PersonAgeAtAttendance', decimal_places=2, max_digits=9,
                                                   null=True, blank=True)

    # TODO PersonNhsNumber in the database? discuss possible spec change
    # `PersonGlobalNumber` NVARCHAR(10) NULL,
    person_global_number = models.CharField(db_column='PersonGlobalNumber', max_length=10, null=True, blank=True)

    # TODO as above
    # `PersonGlobalNumberStatusIndicator` CHAR(2) NULL,
    person_global_number_status_indicator = models.CharField(db_column='PersonGlobalNumberStatusIndicator',
                                                             max_length=2, null=True, blank=True)

    # `PersonIdentityWithheldReason` CHAR(2) NULL,
    person_identity_withheld_reason = models.CharField(db_column='PersonIdentityWithheldReason', max_length=2,
                                                       null=True, blank=True)

    # `PersonLocalNumber` NVARCHAR(20) NULL,
    person_local_number = models.CharField(db_column='PersonLocalNumber', max_length=20, null=True, blank=True)

    # `PersonUsualAddress1` NVARCHAR(35) NULL,
    person_usual_address_1 = models.CharField(db_column='PersonUsualAddress1', max_length=35, null=True, blank=True)

    # `PersonUsualAddress2` NVARCHAR(35) NULL,
    person_usual_address_2 = models.CharField(db_column='PersonUsualAddress2', max_length=35, null=True, blank=True)

    # `PersonUsualAddressPostcode` NVARCHAR(10) NULL,
    person_usual_address_postcode = models.CharField(db_column='PersonUsualAddressPostcode', max_length=10, null=True,
                                                     blank=True)

    # `PersonResidenceOrgCode` NVARCHAR(10) NULL,
    person_residence_org_code = models.CharField(db_column='PersonResidenceOrgCode', max_length=10, null=True,
                                                 blank=True)

    # `PersonUsualResidenceType` NVARCHAR(18) NULL,
    person_usual_residence_type = models.CharField(db_column='PersonUsualResidenceType', max_length=18, null=True,
                                                   blank=True)

    # `PersonResidenceLsoa` NVARCHAR(10) NULL,
    person_residence_lsoa = models.CharField(db_column='PersonResidenceLsoa', max_length=10, null=True, blank=True)

    # `PersonPreferredContact` NVARCHAR(255) NULL,
    person_preferred_contact = XmlCharField(xml_tags=('CONTACT',
                                                      {'mobile': 'MOBILE', 'home': 'HOME', 'email': 'EMAIL'}),
                                            populate_fully=True, db_column='PersonPreferredContact',
                                            max_length=255, null=True, blank=True)

    # `PersonGpPracticeCode` NVARCHAR(6) NULL,
    person_gp_practice_code = models.CharField(db_column='PersonGpPracticeCode', max_length=6, null=True, blank=True)

    # `PersonCommLang` NVARCHAR(18) NULL,
    person_comm_lang = models.CharField(db_column='PersonCommLang', max_length=18, null=True, blank=True)

    # `PersonInterpreterRqd` NVARCHAR(18) NULL,
    person_interpreter_rqd = ValueConverterCharField(from_db=person_interpreter_rqd_from_db,
                                                     to_db=person_interpreter_rqd_to_db,
                                                     # coerce_ui_value=person_interpreter_coerce,
                                                     db_column='PersonInterpreterRqd', max_length=18, null=True,
                                                     blank=True)

    # `PersonInterpreterLang` NVARCHAR(18) NULL,
    person_interpreter_lang = models.CharField(db_column='PersonInterpreterLang', max_length=18, null=True, blank=True)

    # `PersonEthnicCategory` NVARCHAR(2) NULL,
    person_ethnic_category = models.CharField(db_column='PersonEthnicCategory', max_length=2, null=True, blank=True)

    # `PersonSchool` NVARCHAR(10) NULL,
    person_school = models.CharField(db_column='PersonSchool', max_length=10, null=True, blank=True)

    # `PersonCompanion` NVARCHAR(255) NULL,
    person_companion = models.CharField(db_column='PersonCompanion', max_length=255, null=True, blank=True)

    # `PersonSpecialPatientNoteLocal` NVARCHAR(4096) NULL,
    person_special_patient_note_local = models.TextField(db_column='PersonSpecialPatientNoteLocal', null=True,
                                                         blank=True)

    # `PersonAdditionalInformation` NVARCHAR(4096) NULL,
    person_additional_information = models.TextField(db_column='PersonAdditionalInformation', null=True, blank=True)

    # `PersonAllergiesAdverseReaction` NVARCHAR(4096) NULL,
    person_allergies_adverse_reaction = models.TextField(db_column='PersonAllergiesAdverseReaction', null=True,
                                                         blank=True)

    # `PersonComorbidities` NVARCHAR(4096) NULL,
    person_comorbidities = models.TextField(db_column='PersonComorbidities', null=True, blank=True)

    # `PersonCurrentMeds` NVARCHAR(4096) NULL,

NewEmergmed/templates/sackett/add_zone.html
{% extends "sackett/site_base.html" %}
{% load i18n %}

{% block title %}{% trans 'Add new clinical area' %}{% endblock %}

{% block scripts %}
<script type='application/javascript' language='JavaScript'>
    function zone_form_template_select_changed(value, text, $selected) {
        var selectedIndex = -1;

        if (typeof $selected != 'undefined') {
            selectedIndex = parseInt($selected.data('index'));
        }

        for (var i = 0; i < {{ template_count }}; i++) {
            var detailDiv = $('#template_detail_' + i);
            if (i == selectedIndex) {
                detailDiv.show();
            } else {
                detailDiv.hide();
            }
        }
    }

    function zone_form_post(evt)
    {
        var zone_form=$('#zone_form');
        var zone_form_data = zone_form.serialize();
        $.ajax({
            type: 'POST',
            url: zone_form.attr('action'),
            dataType: 'html',
            data: zone_form_data,
            success: function(result)
            {
                $('#zone_form_result').html(result);
                reset_form()
            }
        });

        //don't submit the form
        return false;
    }

    function reset_form() {
        for (var i = 0; i < {{ template_count }}; i++) {
            var detailDiv = $('#template_detail_' + i);
            detailDiv.hide();
        }

        $('#zone_form_zone_label').val('');
        $('#zone_form_template_outer_dropdown').dropdown('restore defaults');
    }

    $('document').ready(function() {
        $('#zone_form_template_outer_dropdown').dropdown({
            onChange: zone_form_template_select_changed
        });

        reset_form();

        $('#zone_form').submit(zone_form_post);
    });
</script>
{% endblock %}

{% block body %}
    <div class="top-padded-frame">
        <div class="ui text container">
            <h2 class="ui dividing header">{% trans 'Add new clinical area' %}</h2>
            <form action="{% url 'sackett:add_zone' %}" method="post" id="zone_form">
                {% csrf_token %}
                <div class="ui middle aligned centered grid">
                    <div class="six wide right aligned column">{{ form.label.label_tag }}</div>
                    <div class="eight wide left aligned column">
                        <div class="ui fluid input">{{ form.label }}</div>
                        {{ form.label.errors }}
                    </div>
                    <div class="two wide right aligned column"></div>
                    <div class="six wide right aligned column">{{ form.template.label_tag }}</div>
                    <div class="eight wide left aligned column">
                        {{ form.template }}
                        {{ form.template.errors }}
                    </div>
                    <div class="two wide right aligned column">
                        <input class="ui primary button" type="submit" value="{% trans 'Add' %}" />
                    </div>
                    <div class="six wide right aligned column"></div>
                    <div class="eight wide left aligned column">
                        {% for t in template_list %}
                        <div id="template_detail_{{ t.index }}">
                            <img src="zoneimg/{{ t.template.image }}" width="200"/>
                            <p>{{ t.template.description }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="two wide right aligned column"></div>
                    <div class="sixteen wide left aligned column">
                        <div id="zone_form_result"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

NewEmergmed/templates/sackett/config_choose_language.html
{#{% extends 'sackett/site_base_no_menu.html' %}#}
{#{% load i18n %}#}
{##}
{#{% block title %}{% trans 'Set site language' %}{% endblock %}#}
{#{% block body %}#}
{#    <div class="ui container primary-container">#}
{#        <h2 class="ui dividing header">{% trans 'Set site language' %}</h2>#}
{#        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}#}
{#            <input name="next" type="hidden" value="{% url 'sackett:default' %}" />#}
{#            <select name="language">#}
{#                {% get_current_language as LANGUAGE_CODE %}#}
{#                {% get_available_languages as LANGUAGES %}#}
{#                {% get_language_info_list for LANGUAGES as languages %}#}
{#                {% for language in languages %}#}
{#                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>#}
{#                        {{ language.name_local }} ({{ language.code }})#}
{#                    </option>#}
{#                {% endfor %}#}
{#            </select>#}
{#            <input type="submit" value="Go" />#}
{#        </form>#}
{#    </div>#}
{#{% endblock %}#}

NewEmergmed/templates/sackett/episode_discharge_early.html
{% load i18n %}

<div class="sixteen wide center aligned column">
    <button class="ui button" type="button" id="early_discharge_button">{% trans 'Discharge early' %}</button>
</div>

NewEmergmed/templates/sackett/episode_new_single_investigation.html
<div class="row" id="new_investigation_select_row">
    <div class="fourteen wide left aligned column">
        {{ form.investigation }}
    </div>
</div>

NewEmergmed/templates/sackett/expected_arrival.html
{% extends "sackett/site_base.html" %}
{% load i18n %}
{% load static %}

{% block meta %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
{% endblock %}

{% block title %}{% trans 'Expected patient' %}{% endblock %}

{% block scripts %}
    <script language="JavaScript" type="application/javascript">
        $('document').ready(function() {
            $('.ui.dropdown').dropdown();
        });
    </script>
{% endblock %}
{% block body %}
    <div class="top-padded-frame">
        <div class="ui text container primary-container no-bottom-border-radius">
            <h2 class="ui dividing header">{% trans 'New patient expected' %}</h2>
            <form action="{% url 'sackett:expected_arrival' %}" method="post">
                {% csrf_token %}
                <div class="ui middle aligned centered stackable grid">
                    <div class="six wide computer only tablet only right aligned column">
                        {{ form.person_given_name.label_tag }}
                    </div>
                    <div class="six wide mobile only left aligned column">{{ form.person_given_name.label_tag }}</div>
                    <div class="eight wide left aligned column">
                        <div class="ui fluid input">
                            {{ form.person_given_name }}
                        </div>
                        {{ form.person_given_name.errors }}
                    </div>
                    <div class="two wide computer only tablet only left aligned column"></div>
                    <div class="six wide computer only tablet only right aligned column">
                        {{ form.person_family_name.label_tag }}
                    </div>
                    <div class="six wide mobile only left aligned column">{{ form.person_family_name.label_tag }}</div>
                    <div class="eight wide left aligned column">
                        <div class="ui fluid input">
                            {{ form.person_family_name }}
                        </div>
                        {{ form.person_family_name.errors }}
                    </div>
                    <div class="two wide computer only tablet only left aligned column"></div>
                    <div class="six wide computer only tablet only right aligned column">
                        {{ form.em_care_chief_complaint.label_tag }}
                    </div>
                    <div class="six wide mobile only left aligned column">{{ form.em_care_chief_complaint.label_tag }}</div>
                    <div class="eight wide left aligned column">
                        {{ form.em_care_chief_complaint }}{{ form.em_care_chief_complaint.errors }}
                    </div>
                    <div class="two wide computer only tablet only left aligned column"></div>
                    <div class="six wide computer only tablet only right aligned column">
                        {{ form.person_stated_gender.label_tag }}
                    </div>
                    <div class="six wide mobile only left aligned column">{{ form.person_stated_gender.label_tag }}</div>
                    <div class="six wide left aligned column">
                        {{ form.person_stated_gender }}{{ form.person_stated_gender.errors }}
                    </div>
                    <div class="four wide computer only tablet only left aligned column"></div>
                    <div class="six wide computer only tablet only right aligned column">
                        {{ form.person_age_at_attendance.label_tag }}
                    </div>
                    <div class="six wide mobile only left aligned column">
                        {{ form.person_age_at_attendance.label_tag }}
                    </div>
                    <div class="six wide left aligned column">
                        <div class="ui fluid input">
                            {{ form.person_age_at_attendance }}
                        </div>
                        {{ form.person_age_at_attendance.errors }}
                    </div>
                    <div class="four wide computer only tablet only left aligned column"></div>
                    <div class="sixteen wide center aligned column">
                        <input class="ui primary button" type="submit" value="{% trans 'Add' %}" />
                    </div>
                </div>
            </form>
        </div>
        <div class="ui text container primary-container no-top-border-radius">
            <h2 class="ui dividing header">{% trans 'Other expected patients' %}</h2>
    {#        <input type="checkbox">{% trans 'Show arrived and deleted (last 24hrs)' %} [TODO: AWAITING AJAX INTEGRATION]</input>#}
            <table class="ui single line celled striped table">
                <thead>
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Information" %}</th>
                        <th class="center aligned">{% trans "Gender" %}</th>
                        <th class="center aligned">{% trans "Age" %}</th>
    {#                    <th>_Del_</th>#}
                    </tr>
                </thead>
            <!-- TODO: Show arrived and deleted (last 24hrs) checkbox -->
            {% for item in expected %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.information }}</td>
                    <td class="center aligned">{{ item.gender }}</td>
                    <td class="center aligned">{{ item.age }}</td>
    {#                <td>&nbsp;</td>#}
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

NewEmergmed/templates/sackett/occupied_bed_template.html
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<div class="ui segment episode bed {% if LANGUAGE_BIDI %}rtl {% endif %}drop-target" draggable="true"
     data-id="{{ drag_data_id }}" data-bed-id="{{ drag_bed_id }}">
    <a href="{% url "sackett:episode" episode.id %}" class="area-anchor">
        <span class="bed-name">
            {{ bed.label }}
        </span>
        <span class="clinician">
            {{ episode.assigned_clinician.first_name }}
            {{ episode.assigned_clinician.last_name }}
        </span>
        <div class="patient-container">
            <span class="patient-name">{{ episode.person_family_name|upper }}, {{ episode.person_given_name }}</span>
            <span class="patient-age">{{ episode.person_age_at_attendance|stringformat:"d" }}</span>
        </div>
        <div class="icon-container">
            {% for state_icon in state_icons %}
                <i class="{{ state_icon.0 }}" data-content="{{ state_icon.1 }}"></i>
            {% endfor %}
        </div>
        <span class="patient-complaint">
            {{ complaint }}
        </span>
    </a>
</div>

NewEmergmed/templates/sackett/user_management_all.html
{% extends "sackett/site_base.html" %}
{% load i18n %}
{% load static %}

{% block meta %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
{% endblock %}

{% block title %}{% trans 'User profile management' %}{% endblock %}

{% block scripts %}
{% endblock %}

{% block body %}
    <div class="top-padded-frame">
        <div class="ui text container primary-container">
            <div class="ui middle aligned grid">
                <div class="sixteen wide left aligned column">
                    <span class="user-mgmt-heading">
                        {% blocktrans %}Users{% endblocktrans %}
                    </span>
                </div>
                <div class="sixteen wide left aligned column">
                    <table class="ui compact celled table">
                        <thead>
                            <tr>
                                <th>{% trans 'Username' %}</th>
                                <th>{% trans 'Enabled' %}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for u in users %}
                            <tr>
                                <td>{{ u.username }}</td>
                                <td>{% if u.is_enabled %}{% trans 'Yes' %}{% else %}{% trans 'No' %}{% endif %}</td>
                                <td>
                                    <button type="button"
                                            onclick="location.href='{% url 'sackett:user_management_edit' u.id %}'">
                                        {% trans 'Edit' %}
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="sixteen wide right aligned column">
                    <button type="button" onclick="location.href='{% url 'sackett:user_management_add' 0 %}'"
                            class="ui button">
                        {% trans 'Add new user' %}
                    </button>
                </div>
                <div class="sixteen wide left aligned column">
                    <span class="user-mgmt-heading">
                        {% blocktrans %}Doctors{% endblocktrans %}
                    </span>
                </div>
                <div class="sixteen wide left aligned column">
                    <table class="ui compact celled table">
                        <thead>
                            <tr>
                                <th>{% trans 'Last Name' %}</th>
                                <th>{% trans 'First Name' %}</th>
                                <th>{% trans 'Enabled' %}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for c in consultants %}
                            <tr>
                                <td>{{ c.last_name }}</td>
                                <td>{{ c.first_name }}</td>
                                <td>{% if c.is_enabled %}{% trans 'Yes' %}{% else %}{% trans 'No' %}{% endif %}</td>
                                <td>
                                    {% if c.is_enabled %}
                                    <button type="button" class="ui button"
                                            onclick="location.href='{% url 'sackett:user_management_disable_doctor' c.id %}'">
                                        {% trans 'Disable' %}
                                    </button>
                                    {% else %}
                                    <button type="button" class="ui button"
                                            onclick="location.href='{% url 'sackett:user_management_enable_doctor' c.id %}'">
                                        {% trans 'Enable' %}
                                    </button>
                                    {% endif %}
                                {% comment %}
                                TODO: confirmation dialog on delete button
                                {% endcomment %}
                                    <button type="button" class="ui right floated negative button"
                                            onclick="location.href='{% url 'sackett:user_management_delete_doctor' c.id %}'">
                                        {% trans 'Delete' %}
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="sixteen wide right aligned column">
                    <button type="button" onclick="location.href='{% url 'sackett:user_management_add' 1 %}'"
                            class="ui button">
                        {% trans 'Add new doctor' %}
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}