NewEmergmed/NewEmergmed/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    re_path(r'^sackett/', include('sackett.urls')),
)

NewEmergmed/sackett/urls.py
from django.urls import re_path
from . import views

app_name = 'sackett'

urlpatterns = [
    re_path(r'debug/import_datatables$', views.debug_import_tables, name='debug_import_tables'),
    re_path(r'debug/import_diagnoses$', views.debug_import_diagnoses, name='debug_import_diagnoses'),
    re_path(r'admin/area/add$', views.add_zone, name='add_zone'),
    re_path(r'admin/area/zoneimg/(?P<image_path>.+\.(jpe?g|gif|png))$', views.zone_image, name='zone_image'),
    re_path(r'arrivals/expected$', views.expected_arrival, name='expected_arrival'),
    re_path(r'arrivals/triage$', views.triage_arrival, name='triage_arrival'),
    # re_path(r'config/language$', views.config_choose_language, name='config_choose_language'),
    re_path(r'episode/(?P<episode_id>[0-9]+)$', views.episode, name='episode'),
    re_path(r'episode/(?P<episode_id>[0-9]+)/patient$', views.patient_details, name='patient_details'),
    re_path(r'episode/(?P<episode_id>[0-9]+)/update$', views.episode_update, name='episode_update'),
    re_path(r'episode/breach/(?P<episode_id>[0-9]+)$', views.episode_breach, name='submit_breach'),
    re_path(r'lock/acquire$', views.lock_acquire, name='lock_acquire'),
    re_path(r'lock/refresh$', views.lock_refresh, name='lock_refresh'),
    re_path(r'lock/release$', views.lock_release, name='lock_release'),
    re_path(r'registration$', views.patient_details_overview, name='patient_details_overview'),
    re_path(r'search/diagnosis/(?P<search>.*)$', views.diagnosis_search, name='diagnosis_search'),
    re_path(r'search/gp/(?P<search>.*)$', views.gp_search, name='gp_search'),
    re_path(r'search/school/(?P<search>.*)$', views.school_search, name='school_search'),
    re_path(r'search/hcfacility/(?P<search>.*)$', views.healthcare_facility_search, name='healthcare_facility_search'),
    re_path(r'user/add/(?P<is_doctor>[0-1])$', views.user_management_add, name='user_management_add'),
    re_path(r'user/delete/(?P<user_id>[0-9]+)$', views.user_management_delete_doctor, name='user_management_delete_doctor'),
    re_path(r'user/disable/(?P<user_id>[0-9]+)$', views.user_management_disable_doctor,
        name='user_management_disable_doctor'),
    re_path(r'user/edit/(?P<user_id>[0-9]+)$', views.user_management_edit_user, name='user_management_edit'),
    re_path(r'user/enable/(?P<user_id>[0-9]+)$', views.user_management_enable_doctor, name='user_management_enable_doctor'),
    re_path(r'user/login$', views.user_management_login, name='login'),
    re_path(r'user/logout$', views.user_management_logout, name='logout'),
    re_path(r'user/manage(/?P<show_inactive>[0-1])?$', views.user_management_all, name='user_management_all'),
    re_path(r'user/profile$', views.user_management_personal, name='user_management_personal'),
    re_path(r'area$', views.zone_summary, name='zone_summary'),
    re_path(r'area/content$', views.zone_summary_content_only, name='zone_summary_content_only'),
    re_path(r'area/(?P<zone_id>[0-9]+)$', views.zone_overview, name='zone_overview'),
    re_path(r'area/(?P<zone_id>[0-9]+)/content$', views.zone_overview_content_only, name='zone_overview_content_only'),
    re_path(r'$', views.zone_summary, name='default'),
    re_path(r'index\.html$', views.zone_summary, name='default_index'),

# still TODO
    re_path(r'admin/discharged$', views.zone_summary, name='view_discharged'),
    re_path(r'admin/export$', views.zone_summary, name='export_data'),
    re_path(r'admin/quality$', views.zone_summary, name='review_breaches'),
    re_path(r'admin/dashboard$', views.zone_summary, name='dashboard'),
    re_path(r'admin/settings$', views.zone_summary, name='modify_org'),
]

NewEmergmed/sackett/views.py
from datetime import date, timedelta
from decimal import Decimal
import os
import mimetypes
from django.contrib.auth import get_user_model, login, logout, update_session_auth_hash
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader
from django.urls import reverse
from django.utils.safestring import SafeString
from django.utils.translation import get_language
from django.utils.translation import gettext as _
from itertools import groupby
import sackett.recordlocking as recordlocking
from NewEmergmed import settings
from . import uniqueid
from .authhelpers import is_user_authorised_for_zone
from .constants import *
from .diagnosisdataimporter import DiagnosisDataImporter
from .diagnosisdataproxy import DiagnosisDataProxy
from .enumerations import LockAcquireResult
from .episodehelpers import *
from .forms import *
from .models import Bed, Breach, Episode, Expected, UserPermissionSupport, Zone
from .picklistdataimporter import PickListDataImporter
from .picklistdataproxy import PickListDataProxy
from .utils import Expando, utc_now
from .zonehelpers import move_episode


# TODO: remove
def debug_import_diagnoses(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'sackett/debug_import_diagnoses.html', context)
    elif request.method == 'POST':
        DiagnosisDataImporter.start_background(get_language())  # do_import(get_language())
        return HttpResponseRedirect(reverse('sackett:debug_import_diagnoses'))


def debug_import_tables(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'sackett/debug_import_tables.html', context)
    elif request.method == 'POST':
        PickListDataImporter.start_background(get_language())   # import_all(get_language())
        return HttpResponseRedirect(reverse('sackett:debug_import_tables'))

# end temporary debugging views


def add_zone(request):
    if request.method == 'POST':
        form = AddZoneForm(request.POST)

        result_template = loader.get_template('sackett/add_zone_result.html')

        if form.is_valid():
            zone_template = next((t for t in form.available_templates
                                 if t['template'] == form.cleaned_data['template']), None)

            if zone_template is not None:
                new_zone = Zone(label=form.cleaned_data['label'],
                                template=zone_template['template'],
                                summary_template=zone_template['summary_template'],
                                deleted=False)
                new_zone.save()

                # add special bed for the waiting list
                waiting_bed = Bed(zone=new_zone,
                                  template_index=-1,
                                  name=ZONE_WAITING_LIST_BED_NAME,
                                  label='')
                waiting_bed.save()

                # add the other beds
                bed_count = 1
                for bed in zone_template['beds']:
                    new_bed = Bed(zone=new_zone,
                                  template_index=bed_count,
                                  name=bed['name'],
                                  label=bed['label'])   # zone_template['beds'][bed])
                    new_bed.save()
                    bed_count += 1
                    
                return HttpResponse(result_template.render({'new_zone_url': '/sackett/area/' + str(new_zone.id),
                                                            'success': True},
                                                           request))
            # TODO: report error
            else:
                return HttpResponse(result_template.render({'success': False}, request))
        else:
            return HttpResponse(result_template.render({'success': False}, request))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = AddZoneForm()

    template_list = [{'template': t, 'index': idx} for idx, t in enumerate(form.available_templates)]

    return render(request, 'sackett/add_zone.html', {'form': form,
                                                     'template_list': template_list,
                                                     'template_count': len(template_list), })


# TODO: allow language selection
# def config_choose_language(request):
#     return render(request, 'sackett/config_choose_language.html')


# AJAX callback point for the diagnosis search function - expects one (space delimited) string with a key of 'search'
def diagnosis_search(request, search):
    if request.method == 'GET':
        diagnoses = DiagnosisDataProxy.lookup_by_terms_string(search)
        return HttpResponse(json.dumps({"success": True,
                                        "results": [{"value": d.code, "name": d.description}
                                                    for d, w in diagnoses]}),
                            content_type='application/json')
    else:
        raise Http404


def episode(request, episode_id):
    episode_object = get_object_or_404(Episode, id=episode_id)

    pre_diagnosis_form = EpisodePreDiagnosisForm(instance=episode_object, user=request.user)

    additional_content = __episode_additional(request, episode_object)
    accordion_content, collapsed_panels = __episode_accordion(request, episode_object)
    state_icon_content = __episode_state_icons(request, episode_object)

    return render(request, 'sackett/episode.html', {'full_name': get_display_name(episode_object),
                                                    'gender': get_gender_icon(episode_object),
                                                    'age': episode_object.person_age_at_attendance or _("??"),
                                                    'unique_id': episode_object.em_care_unique_id,
                                                    'local_number': episode_object.person_local_number,
                                                    'breach_form': EpisodeBreachForm(), # always an empty form
                                                    'pre_diagnosis_form': pre_diagnosis_form,
                                                    'additional_content': additional_content,
                                                    'accordion_content': accordion_content,
                                                    'collapsed_panels': collapsed_panels,
                                                    'episode_id': episode_id,
                                                    'is_discharged':
                                                        episode_object.em_care_depart_date_time is not None,
                                                    'state_icons': state_icon_content
                                                    },
                  )


# AJAX callback point for the breach 'submit' button - expects data in the form { "field": "value", ... }
def episode_breach(request, episode_id):
    if request.method == 'POST':
        episode_object = get_object_or_404(Episode, id=episode_id)
        today_utc = utc_now()
        one_day = timedelta(days=-1)
        last_day_breaches = Breach.objects.filter(episode_id=episode_id, added_date_time__gte=today_utc+one_day)
        if last_day_breaches.count() > 50:      # TODO magic constant
            return HttpResponseBadRequest()

        form = EpisodeBreachForm(request.POST)

        if form.is_valid():
            if len(form.cleaned_data['detail']) > 0:
                breach = Breach(episode=episode_object, narrative=form.cleaned_data['detail'],
                                added_date_time=today_utc)
                breach.save()

            return HttpResponse()
        else:
            return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()


# AJAX callback point for the Episode 'save' button - expects data in the form { "field": "value", ... }
def episode_update(request, episode_id):
    if request.method == 'POST':
        episode_object = get_object_or_404(Episode, id=episode_id)
        old_episode_object = get_object_or_404(Episode, id=episode_id)      # for later comparison to update page

        # hack to allow us to setattr() in the lambda below
        complete_discharge = Expando()
        complete_discharge.value = False
        early_discharge = Expando()
        early_discharge.value = False
        undo_early_discharge = Expando()
        undo_early_discharge.value = False

        field_fns = {       # f = field name in model, p = POST data, pf = key in POST data ('POST field')
                '__complete_discharge__': lambda f, p, pf: setattr(complete_discharge, 'value', True),
                '__early_discharge__': lambda f, p, pf: setattr(early_discharge, 'value', True),
                '__undo_early_discharge__': lambda f, p, pf: setattr(undo_early_discharge, 'value', True),
                'assigned_clinician': lambda f, p, pf: setattr(episode_object, f,
                                                               get_user_model().objects.get(id=p[pf]) if
                                                               p[pf].isdigit() else None),
                'em_care_clinical_narrative':
                lambda f, p, pf: setattr(episode_object, 'em_care_clinical_narrative',
                                         ';'.join((episode_object.em_care_clinical_narrative, p[pf]))),
                'bed': lambda f, p, pf: setattr(episode_object, f,
                                                Bed.objects.get(id=p[pf]))
        }

NewEmergmed/templates/sackett/templatetags/locking_forms.html
<form id="acquire_lock_form" data-id="{{ episode_id }}" action="{% url 'sackett:lock_acquire' %}" method="post">
</form>
<form id="refresh_lock_form" action="{% url 'sackett:lock_refresh' %}" method="post">
</form>
<form id="release_lock_form" action="{% url 'sackett:lock_release' %}" method="post">
</form>

NewEmergmed/templates/sackett/templatetags/locking_messages.html
{% load i18n %}

<div class="ui warning message hidden" id="warning_banner">
    <div class="header" id="record_locked_banner_message">
        {% trans 'Another user is editing this record - please wait a moment' %}
    </div>
</div>
<div class="ui negative message hidden" id="error_banner">
    <div class="header" id="lock_failed_banner_message">
        {% trans 'This record is locked by another user and cannot be edited' %}
    </div>
    <div id="lock_error_banner_message">
        <div class="header" id="lock_error_banner_message">
            {%  trans 'There was an error while locking this record - it cannot be edited and saved at this time' %}
        </div>
        <p>{% trans 'Further attempts will be made automatically - this message will disappear once the record has been successfully locked' %}</p>
    </div>
    <div class="header" id="lock_expired_banner_message">
        {%  trans 'This record has been locked by another user - any unsaved changes you have made will be lost' %}
    </div>
</div>
<div class="ui basic modal" id="record_steal_popup">
    <div class="ui three icon header">
        <i class="lock icon"></i>
        {% trans 'Record locked' %}
    </div>
    <div class="content">
        <div class="description">
            <p>{% trans 'Another user is editing this record. You can take control of it but they will lose any unsaved changes.' %}</p>
            <p>{% trans 'Take control of this record?' %}</p>
        </div>
    </div>
    <div class="actions">
        <div class="ui red basic cancel inverted button" id="record_steal_popup_no_button">
            <i class="remove icon"></i>
            {% trans 'No' %}
        </div>
        <div class="ui green ok inverted button" id="record_steal_popup_yes_button">
            <i class="checkmark icon"></i>
            {% trans 'Yes' %}
        </div>
    </div>
</div>

NewEmergmed/templates/sackett/templatetags/nav_menu.html
{% load static %}
{% load i18n %}

<div class="ui one column grid">
    <div class="computer only tablet only column">
        <div class="ui fixed inverted main menu">
            <a href="{% url 'sackett:default' %}" class="nav-menu-home-link" target="_top">
                <img src="{% static "img/logo.png" %}" class="nav-menu-home-image"/>
            </a>
            <a href="{% url 'sackett:expected_arrival' %}" class="item" target="_top">
                {% trans 'Expected patient' %}
            </a>
            <a href="{% url 'sackett:triage_arrival' %}" class="item" target="_top">
                {% trans 'Triage' %}
            </a>
            <a href="{% url 'sackett:patient_details_overview' %}" class="item" target="_top">
                {% trans 'Registration' %}
            </a>
            <div class="right menu">
                {% if user.is_authenticated %}
                <div class="ui simple vertical dropdown item">
                    <a href="{% url 'sackett:user_management_personal' %}" target="_top">
                        <i class="large user icon no-margin"></i>
                        <span class="nav-menu-username">{{ user.username }}</span>
                    </a>
                    <i class="dropdown icon"></i>
                    <div class="ui menu">
                        <a href="{% url 'sackett:user_management_personal' %}" class="item" target="_top">
                            {% trans 'Account' %}
                        </a>
                        {% if perms.sackett.can_administer_users %}
                        <a href="{% url 'sackett:user_management_all' %}" class="item" target="_top">
                            {% trans 'User admin' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_export_data %}
                        <a href="{% url 'sackett:export_data' %}" class="item" target="_top">
                            {% trans 'Export data' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_review_breaches %}
                        <a href="{% url 'sackett:review_breaches' %}" class="item" target="_top">
                            {% trans 'Quality review' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_view_dashboard %}
                        <a href="{% url 'sackett:dashboard' %}" class="item" target="_top">
                            {% trans 'Dashboard' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_undischarge %}
                        <a href="{% url 'sackett:view_discharged' %}" class="item" target="_top">
                            {% trans 'Discharged patients' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_modify_org %}
                        <a href="{% url 'sackett:modify_org' %}" class="item" target="_top">
                            {% trans 'Settings' %}
                        </a>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <a href="{% url 'sackett:login' %}" class="item" target="_top">
                    <i class="large sign in icon no-margin"></i>
                </a>
                {% endif %}
                <div class="ui simple vertical dropdown item">
                    {% trans 'Clinical areas' %}
                    <i class="dropdown icon"></i>
                    <div class="ui menu">
                        {% for zone in zones %}
                            <a href="{% url 'sackett:zone_overview' zone.id %}" class="item" target="_top">
                                {{ zone.label }}
                            </a>
                        {% endfor %}
                        {% if perms.sackett.can_administer_zones %}
                            <a href="{% url 'sackett:add_zone' %}" class="item" target="_top">
                                {% trans 'Add new...' %}
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile only column">
        <div class="ui fixed inverted main menu">
            <a href="{% url 'sackett:default' %}" class="item" target="_top">
                {% trans 'Overview' %}
            </a>
            <a href="{% url 'sackett:expected_arrival' %}" class="item" target="_top">
                {% trans 'Expected' %}
            </a>
            <a href="{% url 'sackett:triage_arrival' %}" class="item" target="_top">
                {% trans 'Triage' %}
            </a>
            <a href="{% url 'sackett:patient_details_overview' %}" class="item" target="_top">
                {% trans 'Reg' %}
            </a>
            <div class="right menu">
                {% if user.is_authenticated %}
                <div class="ui simple vertical dropdown item">
                    <a href="{% url 'sackett:user_management_personal' %}" class="horizontal slim fitted item"
                       target="_top">
                        <i class="user icon no-margin"></i>
                    </a>
                    <i class="dropdown icon"></i>
                    <div class="ui menu">
                        <a href="{% url 'sackett:user_management_personal' %}" class="item" target="_top">
                            {% trans 'Account' %}
                        </a>
                        {% if perms.sackett.can_administer_users %}
                        <a href="{% url 'sackett:user_management_all' %}" class="item" target="_top">
                            {% trans 'User admin' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_export_data %}
                        <a href="{% url 'sackett:export_data' %}" class="item" target="_top">
                            {% trans 'Export data' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_review_breaches %}
                        <a href="{% url 'sackett:review_breaches' %}" class="item" target="_top">
                            {% trans 'Quality review' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_view_dashboard %}
                        <a href="{% url 'sackett:dashboard' %}" class="item" target="_top">
                            {% trans 'Dashboard' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_undischarge %}
                        <a href="{% url 'sackett:view_discharged' %}" class="item" target="_top">
                            {% trans 'Discharged patients' %}
                        </a>
                        {% endif %}
                        {% if perms.sackett.can_modify_org %}
                        <a href="{% url 'sackett:modify_org' %}" class="item" target="_top">
                            {% trans 'Settings' %}
                        </a>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <a href="{% url 'sackett:login' %}" class="horizontal slim fitted item" target="_top">
                    <i class="sign in icon no-margin"></i>
                </a>
                {% endif %}
                <div class="ui simple vertical dropdown item">
                    {% trans 'Areas' %}
                    <i class="dropdown icon"></i>
                    <div class="ui menu">
                        {% for zone in zones %}
                            <a href="{% url 'sackett:zone_overview' zone.id %}" class="item" target="_top">
                                {{ zone.label }}
                            </a>
                        {% endfor %}
                        {% if perms.sackett.can_administer_zones %}
                            <a href="{% url 'sackett:add_zone' %}" class="item" target="_top">
                                {% trans 'Add new...' %}
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>